export const TIMINGS = {
  COUNTDOWN_DURATION: 3,
  MIN_WORK_DURATION: 5,
  MAX_WORK_DURATION: 300, // 5 minutes (covers 4 minutes requirement)
  MIN_REST_DURATION: 5,
  MAX_REST_DURATION: 300, // 5 minutes
  MIN_ROUNDS: 1,
  MAX_ROUNDS: 50,
  MIN_WARM_UP: 0,
  MAX_WARM_UP: 600, // 10 minutes
  MIN_COOL_DOWN: 0,
  MAX_COOL_DOWN: 600, // 10 minutes
  UI_UPDATE_INTERVAL: 100,
  BACKGROUND_SAVE_INTERVAL: 5000,
  DRIFT_CORRECTION_THRESHOLD: 100,
} as const;

